#!/usr/bin/env node
/**
 * Emits llms.txt (and llms-full.txt) for the GitHub Pages site
 * (https://shinyaigeek.github.io/qain/llms.txt), following the llmstxt.org
 * convention: a curated, LLM-friendly map of the project at the site root, plus
 * a single-file concatenation of every doc for one-fetch consumption.
 *
 * llms-full.txt is built from the real Markdown so it never drifts from the
 * docs; the map's one-line descriptions are curated here.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const ROOT = new URL('../', import.meta.url).pathname
const SITE = 'https://shinyaigeek.github.io/qain'
const REPO = 'https://github.com/Shinyaigeek/qain'
const outDir = process.argv[2] ?? 'site'

// Reading order; `page` is the rendered doc on the site, `file` the source md.
const DOCS = [
  {
    file: 'README.md',
    page: `${SITE}/docs/`,
    label: 'Documentation overview',
    desc: 'Index of the usage docs and links to the test-runner integrations.',
  },
  {
    file: 'getting-started.md',
    page: `${SITE}/docs/getting-started.html`,
    label: 'Getting started',
    desc: 'Install, capture your first snapshot, and read your first diff.',
  },
  {
    file: 'cli.md',
    page: `${SITE}/docs/cli.html`,
    label: 'CLI reference',
    desc: 'Every command and flag: snap, diff, view, shot — and the exit codes.',
  },
  {
    file: 'recipes.md',
    page: `${SITE}/docs/recipes.html`,
    label: 'Recipes',
    desc:
      'Snapshot a dev server, scope to one element, point at a Storybook story, ' +
      'extract computed styles as data, and gate CI or a coding agent on the exit code.',
  },
  {
    file: 'github-action.md',
    page: `${SITE}/docs/github-action.html`,
    label: 'GitHub Action',
    desc:
      'The qain-diff action: a sticky PR comment with the semantic diff and ' +
      'before/after/diff screenshots whenever a committed baseline changes.',
  },
  {
    file: 'snapshot-format.md',
    page: `${SITE}/docs/snapshot-format.html`,
    label: 'Snapshot & diff format',
    desc: 'The stable, documented JSON the CLI reads and writes.',
  },
  {
    file: 'library.md',
    page: `${SITE}/docs/library.html`,
    label: 'Library API (@qain/core)',
    desc: 'Capture and diff from your own code, with Playwright, Puppeteer, or a raw CDP socket.',
  },
]

const SUMMARY =
  'Semantic style-regression testing for Chromium. qain captures the browser’s ' +
  '*used values* — resolved computed styles, layout boxes, paint order, composited ' +
  'colors — as a JSON snapshot, and diffs two snapshots semantically: it reports ' +
  'what changed and what merely moved, attributing each change to the CSS declaration ' +
  'behind it. Not pixels.'

const DETAIL =
  'qain is built for humans and coding agents alike: the diff is plain text, the exit ' +
  'code is 1 when the diff is non-empty (so CI and agents can gate on it), and the ' +
  'snapshot is stable, documented JSON that scripts can consume without qain on the ' +
  'other end. It suppresses noise structurally — elements are keyed not positioned, ' +
  'class strings are captured but never compared, and every change is labelled primary ' +
  'or derived so collateral movement folds away. Chromium-only by design: it is built ' +
  'on DOMSnapshot.captureSnapshot and CSS.forcePseudoState, which have no Firefox or ' +
  'WebKit equivalent.'

function mapDoc(d) {
  return `- [${d.label}](${d.page}): ${d.desc}`
}

const llms = `# qain

> ${SUMMARY}

${DETAIL}

## Documentation

${DOCS.map(mapDoc).join('\n')}

## Test-runner integrations

- [@qain/playwright](${REPO}/blob/main/packages/playwright/README.md): \`toMatchStyleSnapshot\` for Playwright tests.
- [@qain/vitest](${REPO}/blob/main/packages/vitest/README.md): the same matcher for Vitest browser mode — component VRT without booting Storybook.
- [@qain/storybook](${REPO}/blob/main/packages/storybook/README.md): \`matchStyleSnapshot\` for the Storybook test runner — every story becomes a style test.

## Try it

- [Live demo](${SITE}/): a billing page broken four ways at once, with the replay diff, HTML report, terminal output, and raw snapshots — regenerated by CI.
- [In-browser playground](${SITE}/playground/): edit a self-contained HTML page and watch qain diff it live, entirely in the browser — no server, no CDP.

## Optional

- [Design story (main README)](${REPO}/blob/main/README.md): why the diff stays quiet, how rule attribution works, what replay does, and what qain deliberately does not do.
- [All documentation as one file](${SITE}/llms-full.txt): every doc concatenated for one-fetch consumption.
- [Source repository](${REPO})
`

// --- llms-full.txt: the real Markdown, concatenated ------------------------

const FULL_SOURCES = [
  { path: join(ROOT, 'README.md'), title: 'README.md — the design story' },
  ...DOCS.map((d) => ({ path: join(ROOT, 'docs', d.file), title: `docs/${d.file}` })),
]

let full = `# qain — full documentation

> ${SUMMARY}

This file concatenates the qain README and every page under docs/, in reading
order, for one-fetch consumption by an LLM. Source: ${REPO}
`

for (const s of FULL_SOURCES) {
  const md = (await readFile(s.path, 'utf8')).trim()
  full += `\n\n\n---\n\n<!-- source: ${s.title} -->\n\n${md}\n`
}

// --- write -----------------------------------------------------------------

await mkdir(outDir, { recursive: true })
await writeFile(join(outDir, 'llms.txt'), llms)
await writeFile(join(outDir, 'llms-full.txt'), full)
process.stderr.write(
  `llms: ${join(outDir, 'llms.txt')} (${llms.length} B) + ` +
    `${join(outDir, 'llms-full.txt')} (${full.length} B)\n`,
)
